import { useEffect, useState } from "react";
import { BellRing, Check, Loader2, Mail, SlidersHorizontal, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { formatDate } from "@/lib/format";
import { Link } from "wouter";

export function CustomerRestockAlerts() {
  const utils = trpc.useUtils();
  const { data: alerts, isLoading } = trpc.store.restockAlerts.useQuery();
  const cancel = trpc.store.cancelRestockAlert.useMutation({ onSuccess: () => { toast.success("Back-in-stock alert removed"); void utils.store.restockAlerts.invalidate(); }, onError: error => toast.error(error.message) });
  return <section className="rounded-3xl border border-white/8 bg-[#101821] p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><BellRing className="mt-0.5 h-5 w-5 text-cyan-300" /><div><h2 className="font-black text-white">Back-in-stock alerts</h2><p className="mt-1 text-sm text-slate-500">Manage products you want us to email you about.</p></div></div><Link href="/account/settings" className="inline-flex items-center gap-2 text-xs font-bold text-cyan-300 hover:text-cyan-200"><SlidersHorizontal className="h-3.5 w-3.5" />Preferences</Link></div>{isLoading ? <div className="grid min-h-28 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-cyan-300" /></div> : alerts?.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{alerts.map(alert => <div key={alert.id} className="flex gap-3 rounded-2xl border border-white/8 bg-black/15 p-3"><img src={alert.product?.images?.[0] ?? "/manus-storage/hero-gadgets_4fcc5ee6.jpeg"} alt={alert.product?.name ?? "Product"} className="h-16 w-16 rounded-xl object-cover" /><div className="min-w-0 flex-1"><Link href={alert.product?.slug ? `/products/${alert.product.slug}` : "/shop"} className="block truncate text-sm font-black text-white hover:text-cyan-300">{alert.product?.name ?? "Product unavailable"}</Link><p className="mt-1 text-xs text-slate-500">Requested {formatDate(alert.requestedAt)}</p><p className="mt-1 text-[11px] font-bold capitalize text-amber-300">{alert.status} alert</p></div><button type="button" disabled={cancel.isPending} onClick={() => cancel.mutate({ requestId: alert.id })} className="self-start rounded-lg p-2 text-slate-500 transition hover:bg-red-300/10 hover:text-red-300 disabled:opacity-50" aria-label={`Remove alert for ${alert.product?.name ?? "product"}`}><X className="h-4 w-4" /></button></div>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-white/10 bg-black/10 px-4 py-7 text-center"><p className="text-sm font-bold text-white">No active alerts.</p><p className="mt-1 text-xs text-slate-500">Use Notify Me on an out-of-stock product to add one.</p><Link href="/shop" className="mt-4 inline-flex text-xs font-bold text-cyan-300">Browse products</Link></div>}</section>;
}

export function EmailPreferencesPanel() {
  const utils = trpc.useUtils();
  const { data: preferences, isLoading } = trpc.store.emailPreferences.useQuery();
  const [enabled, setEnabled] = useState(true);
  useEffect(() => { if (preferences) setEnabled(preferences.alertEmailsEnabled); }, [preferences]);
  const update = trpc.store.updateEmailPreferences.useMutation({ onSuccess: result => { setEnabled(result.alertEmailsEnabled); toast.success(result.alertEmailsEnabled ? "Back-in-stock emails enabled" : "You are unsubscribed from back-in-stock emails"); void utils.store.emailPreferences.invalidate(); void utils.store.restockAlerts.invalidate(); }, onError: error => toast.error(error.message) });
  if (isLoading) return <section className="grid min-h-40 place-items-center rounded-3xl border border-white/8 bg-[#101821]"><Loader2 className="h-6 w-6 animate-spin text-cyan-300" /></section>;
  return <section className="rounded-3xl border border-white/8 bg-[#101821] p-5 sm:p-7"><div className="flex items-start gap-3"><Mail className="mt-0.5 h-5 w-5 text-cyan-300" /><div><h2 className="font-black text-white">Email preferences</h2><p className="mt-1 text-sm text-slate-500">Control transactional back-in-stock alerts for {preferences?.email}.</p></div></div><div className="mt-6 flex items-center justify-between gap-4 rounded-2xl border border-white/8 bg-black/15 p-4"><div><p className="text-sm font-black text-white">Back-in-stock alerts</p><p className="mt-1 text-xs leading-5 text-slate-500">Receive one email when a product you requested becomes available.</p></div><button type="button" role="switch" aria-checked={enabled} disabled={update.isPending} onClick={() => update.mutate({ alertEmailsEnabled: !enabled })} className={`relative h-7 w-12 shrink-0 rounded-full transition ${enabled ? "bg-cyan-400" : "bg-slate-700"} disabled:opacity-60`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${enabled ? "left-6" : "left-1"}`} /></button></div>{update.isPending && <p className="mt-3 flex items-center gap-2 text-xs font-bold text-cyan-300"><Loader2 className="h-3.5 w-3.5 animate-spin" />Saving preferences…</p>}<div className="mt-5 flex items-center gap-2 text-xs text-slate-500"><Check className="h-3.5 w-3.5 text-cyan-300" />Changes apply to future and active alerts.</div></section>;
}

export function SettingsHeader() { return <div className="flex items-center gap-3"><Link href="/account" className="text-xs font-bold text-slate-500 hover:text-cyan-300">Account</Link><span className="text-slate-700">/</span><span className="text-xs font-bold text-cyan-300">Settings</span></div>; }
