import { useAuth } from "@/_core/hooks/useAuth";
import CustomerAuthDialog from "@/components/storefront/CustomerAuthDialog";
import { formatDate, formatNpr } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Loader2, PackageSearch, UserRoundCheck } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";

const statusStyles: Record<string, string> = { pending: "bg-amber-300/10 text-amber-300", confirmed: "bg-cyan-300/10 text-cyan-300", shipped: "bg-violet-300/10 text-violet-300", delivered: "bg-emerald-300/10 text-emerald-300", cancelled: "bg-red-300/10 text-red-300" };

export default function Account() {
  const { user, loading, logout } = useAuth();
  const [authOpen, setAuthOpen] = useState(false);
  const { data: orders, isLoading } = trpc.store.accountOrders.useQuery(undefined, { enabled: Boolean(user) });
  if (loading) return <main className="container grid min-h-[500px] place-items-center"><Loader2 className="h-7 w-7 animate-spin text-cyan-300" /></main>;
  if (!user) return <><main className="container grid min-h-[540px] place-items-center py-16"><div className="max-w-md text-center"><UserRoundCheck className="mx-auto h-11 w-11 text-cyan-300" /><h1 className="mt-5 text-3xl font-black text-white">Your drops, in one place.</h1><p className="mt-3 text-sm leading-6 text-slate-400">Sign in or create a customer account to see delivery updates, receipts, and your Nexus Drop order history.</p><button onClick={() => setAuthOpen(true)} className="mt-6 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-black text-[#061014]">Login / Create account</button></div></main><CustomerAuthDialog open={authOpen} onOpenChange={setAuthOpen} onAuthenticated={() => window.location.reload()} /></>;
  return <main className="container py-10 sm:py-14"><div className="flex flex-col justify-between gap-5 border-b border-white/8 pb-7 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.17em] text-cyan-300">Nexus account</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em] text-white">Hi, {user.name?.split(" ")[0] || "there"}.</h1><p className="mt-2 text-sm text-slate-400">Track your active drops and view your order history.</p></div><button onClick={logout} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-bold text-slate-300 transition hover:border-red-300/40 hover:text-red-300">Sign out</button></div><section className="mt-8 rounded-3xl border border-white/8 bg-[#101821] p-5 sm:p-7"><div className="flex items-center gap-3"><PackageSearch className="h-5 w-5 text-cyan-300" /><h2 className="font-black text-white">Order history</h2></div>{isLoading ? <div className="grid min-h-48 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-cyan-300" /></div> : orders?.length ? <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-white/8 text-xs uppercase tracking-[.12em] text-slate-500"><tr><th className="pb-3 font-bold">Order</th><th className="pb-3 font-bold">Date</th><th className="pb-3 font-bold">Payment</th><th className="pb-3 font-bold">Total</th><th className="pb-3 font-bold">Delivery</th></tr></thead><tbody className="divide-y divide-white/8">{orders.map(order => <tr key={order.id}><td className="py-4 font-bold text-white">{order.order_number}</td><td className="py-4 text-slate-400">{formatDate(order.createdAt)}</td><td className="py-4 text-slate-400">{order.payment_method}</td><td className="py-4 font-bold text-white">{formatNpr(Number(order.total_amount))}</td><td className="py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${statusStyles[order.order_status] ?? statusStyles.pending}`}>{order.order_status}</span></td></tr>)}</tbody></table></div> : <div className="py-14 text-center"><p className="font-bold text-white">No orders yet.</p><p className="mt-2 text-sm text-slate-500">Your confirmed orders will appear here with their delivery status.</p><Link href="/" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-cyan-300">Shop latest drops <ArrowRight className="h-4 w-4" /></Link></div>}</section></main>;
}
