import ProductCard from "@/components/storefront/ProductCard";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Gem, Glasses, Loader2, MessageCircle, PackageCheck, ShieldCheck, Sparkles, Truck, Watch, Zap } from "lucide-react";
import { Link } from "wouter";

const heroImage = "/manus-storage/hero-gadgets_4fcc5ee6.jpeg";

export default function Home() {
  const { data: products, isLoading } = trpc.store.catalog.useQuery({ sort: "newest" });
  return <main>
    <section className="relative isolate overflow-hidden border-b border-white/8 bg-[#0b121a]"><div className="absolute inset-0"><img src={heroImage} alt="Dark tech accessories arranged on a black background" className="h-full w-full object-cover object-center opacity-35" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_30%,rgba(6,182,212,.33),transparent_23%),linear-gradient(90deg,#0A0A0A_10%,rgba(10,10,10,.84)_43%,rgba(10,10,10,.36)_100%)]" /></div><div className="container relative flex min-h-[560px] items-center py-20 sm:min-h-[630px]"><div className="max-w-2xl"><div className="inline-flex items-center gap-2 rounded-full border border-cyan-300/25 bg-cyan-300/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.16em] text-cyan-200"><Sparkles className="h-3.5 w-3.5" />New Nepal drops</div><h1 className="mt-6 text-5xl font-black leading-[.9] tracking-[-.06em] text-white sm:text-7xl">LATEST<br /><span className="text-cyan-300">DROPS.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-300 sm:text-lg">Streetwear jewelry, everyday carry, and angular accessories selected for your rotation.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/shop" className="inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3.5 text-sm font-black text-[#061014] transition hover:bg-cyan-300 active:scale-[.98]">Shop collection <ArrowRight className="h-4 w-4" /></Link><Link href="/collections/jewelry" className="rounded-xl border border-white/15 bg-white/5 px-5 py-3.5 text-sm font-bold text-white transition hover:bg-white/10">Explore jewelry</Link></div><div className="mt-12 grid max-w-xl grid-cols-3 gap-3 border-t border-white/10 pt-6 text-xs text-slate-400"><p><span className="block text-lg font-black text-white">Up to 30%</span>off selected drops</p><p><span className="block text-lg font-black text-white">24h</span>Nepalgunj dispatch</p><p><span className="block text-lg font-black text-white">COD</span>available</p></div></div></div></section>
    <section className="border-b border-white/8 bg-[#0d151e]"><div className="container grid gap-px bg-white/8 py-px sm:grid-cols-3"><TrustBadge icon={<Truck />} title="Dispatched from Nepalgunj" copy="Quick handling on every order" /><TrustBadge icon={<PackageCheck />} title="COD Available" copy="Pay when your order arrives" /><TrustBadge icon={<MessageCircle />} title="WhatsApp Support" copy="Direct help for every query" /></div></section>
    <section className="container py-14 sm:py-20"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.17em] text-cyan-300">Build your rotation</p><h2 className="mt-2 text-3xl font-black tracking-[-.04em] text-white sm:text-4xl">Shop by category.</h2></div><Link href="/shop" className="inline-flex items-center gap-2 text-sm font-black text-cyan-300">View the full shop <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><CategoryLink href="/collections/jewelry" title="Jewelry" copy="Metal details and clean lines" icon={<Gem className="h-5 w-5" />} /><CategoryLink href="/collections/watches" title="Watches" copy="Timepieces with presence" icon={<Watch className="h-5 w-5" />} /><CategoryLink href="/collections/eyewear" title="Eyewear" copy="Angular lenses, everyday shade" icon={<Glasses className="h-5 w-5" />} /><CategoryLink href="/collections/bags" title="Bags" copy="Carry less. Move more." icon={<BriefcaseBusiness className="h-5 w-5" />} /></div></section>
    <section className="border-y border-white/8 bg-[#0d151e]"><div className="container py-16 sm:py-20"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.17em] text-cyan-300">Just landed</p><h2 className="mt-2 text-3xl font-black tracking-[-.04em] text-white sm:text-4xl">Featured drops.</h2><p className="mt-3 max-w-xl text-sm text-slate-400">A quick first look—open the Shop page to filter every collection.</p></div><Link href="/shop" className="inline-flex items-center gap-2 text-sm font-black text-cyan-300">Explore all drops <ArrowRight className="h-4 w-4" /></Link></div>{isLoading ? <div className="grid min-h-64 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-cyan-300" /></div> : <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{products?.slice(0, 4).map(product => <ProductCard key={product.id} product={product} />)}</div>}</div></section>
    <section className="container grid gap-10 py-16 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.17em] text-cyan-300">Built for everyday movement</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em] text-white sm:text-4xl">Keep the essentials close. Leave the excess behind.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-slate-400">Every drop is selected for practical wear, strong visual character, and easy styling—from compact carry to the finishing details.</p></div><div className="grid gap-3 sm:grid-cols-2"><Feature title="Quality inspected" icon={<ShieldCheck />} /><Feature title="Fast fulfillment" icon={<Zap />} /><Feature title="Secure checkout" icon={<BadgeCheck />} /><Feature title="Transparent pricing" icon={<Sparkles />} /></div></section>
  </main>;
}

function TrustBadge({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="flex gap-3 bg-[#0d151e] px-4 py-5 sm:px-7"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-cyan-300/10 text-cyan-300">{icon}</div><div><p className="text-sm font-bold text-white">{title}</p><p className="mt-1 text-xs text-slate-500">{copy}</p></div></div>; }
function Feature({ icon, title }: { icon: React.ReactNode; title: string }) { return <div className="flex items-center gap-3 rounded-2xl border border-white/8 bg-[#101821] p-4 text-sm font-bold text-white"><span className="text-cyan-300">{icon}</span>{title}</div>; }
function CategoryLink({ href, title, copy, icon }: { href: string; title: string; copy: string; icon: React.ReactNode }) { return <Link href={href} className="group rounded-2xl border border-white/8 bg-[#101821] p-5 transition hover:-translate-y-1 hover:border-cyan-300/40 hover:bg-[#142230]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300/10 text-cyan-300">{icon}</span><p className="mt-8 font-black text-white">{title}</p><p className="mt-1 text-sm text-slate-500">{copy}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.12em] text-cyan-300">Shop <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-1" /></span></Link>; }
