import { formatNpr } from "@/lib/format";
import { CheckCircle2, CircleDot, PackageCheck, Truck } from "lucide-react";
import { Link } from "wouter";

type Confirmation = { orderNumber: string; totalAmount: number; orderStatus: string };

export default function OrderConfirmation() {
  const saved = sessionStorage.getItem("nexus-drop-last-order");
  const order = saved ? JSON.parse(saved) as Confirmation : null;
  return <main className="container py-12 sm:py-20"><div className="mx-auto max-w-2xl"><div className="rounded-[2rem] border border-cyan-300/20 bg-[radial-gradient(circle_at_top,rgba(6,182,212,.15),transparent_45%),#101821] p-7 text-center sm:p-12"><CheckCircle2 className="mx-auto h-14 w-14 text-cyan-300" /><p className="mt-5 text-xs font-black uppercase tracking-[.18em] text-cyan-300">Order received</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em] text-white">You’re on the list.</h1><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-slate-400">We have received your order. Digital-payment receipts are verified before we confirm dispatch.</p>{order && <div className="mx-auto mt-7 max-w-md rounded-2xl border border-white/10 bg-black/20 p-5 text-left"><p className="text-xs font-bold uppercase tracking-[.12em] text-slate-500">Order reference</p><p className="mt-1 text-xl font-black text-white">{order.orderNumber}</p><p className="mt-4 flex justify-between text-sm text-slate-400"><span>Order total</span><span className="font-bold text-white">{formatNpr(order.totalAmount)}</span></p></div>}<Link href="/account" className="mt-8 inline-flex rounded-xl bg-cyan-400 px-5 py-3 text-sm font-black text-[#061014]">View account orders</Link></div><div className="mt-9 rounded-3xl border border-white/8 bg-[#101821] p-6 sm:p-8"><h2 className="font-black text-white">Delivery tracking</h2><div className="mt-7 grid gap-7 sm:grid-cols-3"><Tracking icon={<CircleDot />} title="Order received" copy="Your request is logged." active /><Tracking icon={<PackageCheck />} title="Confirmed" copy="We check payment and stock." /><Tracking icon={<Truck />} title="Dispatched" copy="Leaves Nepalgunj in 24h." /></div></div></div></main>;
}
function Tracking({ icon, title, copy, active }: { icon: React.ReactNode; title: string; copy: string; active?: boolean }) { return <div className="relative"><div className={`grid h-10 w-10 place-items-center rounded-full ${active ? "bg-cyan-400 text-[#061014]" : "bg-white/8 text-slate-500"}`}>{icon}</div><p className="mt-3 text-sm font-bold text-white">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{copy}</p></div>; }
