import { ArrowLeft, BadgeCheck, PackageCheck, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";

type PolicyKey = "delivery" | "returns" | "terms";

const content: Record<PolicyKey, { eyebrow: string; title: string; intro: string; icon: React.ReactNode; sections: Array<{ heading: string; copy: string }> }> = {
  delivery: { eyebrow: "Store policy", title: "Delivery, clearly explained.", intro: "Every Nexus Drop order is checked before it leaves Nepalgunj. We will keep you informed as its delivery status changes.", icon: <PackageCheck className="h-5 w-5" />, sections: [{ heading: "Dispatch", copy: "In-stock orders are prepared from Nepalgunj. We aim to dispatch orders within 24 hours after COD confirmation or payment verification." }, { heading: "Delivery charge", copy: "Standard delivery is Rs. 150. Delivery becomes free automatically when your order subtotal exceeds Rs. 3000." }, { heading: "Tracking", copy: "Your account order history shows the current status: pending, confirmed, shipped, or delivered. For immediate help, contact us on WhatsApp." }] },
  returns: { eyebrow: "Store policy", title: "Returns and refunds.", intro: "We want each drop to arrive as expected. Contact Nexus Drop promptly if there is an issue with your order.", icon: <BadgeCheck className="h-5 w-5" />, sections: [{ heading: "Before requesting a return", copy: "Keep the product, its accessories, and original packaging in the condition received. Please take clear photos of any issue." }, { heading: "How to get help", copy: "Send your order number and photos to our WhatsApp support. We will review the request and explain the next step before asking you to ship anything." }, { heading: "Approved refunds", copy: "Once an eligible return is reviewed, we will confirm the refund method and timeline directly with you." }] },
  terms: { eyebrow: "Store policy", title: "Terms of service.", intro: "These terms help keep ordering, payment verification, and delivery clear for every Nexus Drop customer.", icon: <ShieldCheck className="h-5 w-5" />, sections: [{ heading: "Orders", copy: "Orders are subject to stock availability. We will contact you if an item becomes unavailable before confirmation." }, { heading: "Digital payments", copy: "For eSewa and bank transfer, upload a valid receipt after payment. Digital orders are confirmed after the payment proof is reviewed." }, { heading: "Support", copy: "For questions about an order, delivery, payment, or product, contact Nexus Drop through the official WhatsApp support link." }] },
};

export default function Policy() {
  const [, params] = useRoute("/policies/:policy");
  const policy = (params?.policy && params.policy in content ? params.policy : "delivery") as PolicyKey;
  const page = content[policy];
  return <main className="container py-10 sm:py-16"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-400 transition hover:text-cyan-300"><ArrowLeft className="h-4 w-4" />Back to storefront</Link><div className="mt-10 grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><aside className="h-fit rounded-3xl border border-cyan-300/15 bg-cyan-300/[.04] p-6 sm:p-8"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-cyan-300/10 text-cyan-300">{page.icon}</div><p className="mt-6 text-xs font-black uppercase tracking-[.17em] text-cyan-300">{page.eyebrow}</p><h1 className="mt-3 text-4xl font-black leading-[.95] tracking-[-.05em] text-white">{page.title}</h1><p className="mt-5 text-sm leading-7 text-slate-300">{page.intro}</p><a href="https://wa.me/9779769279600?text=Hi%20Nexus%20Drop,%20I%20need%20help%20with%20a%20store%20policy" target="_blank" rel="noreferrer" className="mt-7 inline-flex rounded-xl bg-cyan-400 px-4 py-3 text-sm font-black text-[#061014]">Ask on WhatsApp</a></aside><article className="rounded-3xl border border-white/8 bg-[#101821] p-6 sm:p-9"><div className="space-y-8">{page.sections.map(section => <section key={section.heading}><h2 className="text-lg font-black text-white">{section.heading}</h2><p className="mt-3 text-sm leading-7 text-slate-400">{section.copy}</p></section>)}</div></article></div></main>;
}
