import { trpc } from "@/lib/trpc";
import { ArrowRight, ChevronRight, Filter, Loader2, Search, SlidersHorizontal, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";
import ProductCard from "@/components/storefront/ProductCard";

const categoryCopy: Record<string, { eyebrow: string; title: string; description: string }> = {
  jewelry: { eyebrow: "Metal focus", title: "Jewelry with presence.", description: "Polished details for the finishing move." },
  watches: { eyebrow: "Time, refined", title: "Watches for the rotation.", description: "Everyday timepieces with clean visual weight." },
  eyewear: { eyebrow: "Lenses on", title: "Eyewear with edge.", description: "Sharp shape, clear intention, easy daily wear." },
  bags: { eyebrow: "Carry less", title: "Bags made to move.", description: "Compact carry for your necessary pieces." },
};

export default function Shop() {
  const [, params] = useRoute("/collections/:category");
  const slug = params?.category ?? "";
  const [, setLocation] = useLocation();
  const initialParams = useMemo(() => new URLSearchParams(window.location.search), []);
  const [searchDraft, setSearchDraft] = useState(() => initialParams.get("search") ?? "");
  const [searchTerm, setSearchTerm] = useState(searchDraft);
  const [minPrice, setMinPrice] = useState(() => initialParams.get("minPrice") ?? "");
  const [maxPrice, setMaxPrice] = useState(() => initialParams.get("maxPrice") ?? "");
  const [sort, setSort] = useState<"newest" | "price-low" | "price-high">("newest");
  const input = useMemo(() => ({ category: slug || undefined, search: searchTerm.trim() || undefined, minPrice: minPrice ? Number(minPrice) : undefined, maxPrice: maxPrice ? Number(maxPrice) : undefined, sort }), [slug, searchTerm, minPrice, maxPrice, sort]);
  const { data: products, isLoading, error } = trpc.store.catalog.useQuery(input);
  const { data: categories } = trpc.store.categories.useQuery();
  const activeFilters = Boolean(searchTerm || minPrice || maxPrice);
  const catalogPage = { eyebrow: "Nexus Drop catalog", title: searchTerm ? `Search: ${searchTerm}` : "Shop every drop.", description: searchTerm ? "Results matching your current search." : "Find the piece that fits your rotation, then narrow it by price." };
  const page = slug ? (categoryCopy[slug] ?? catalogPage) : catalogPage;
  const goToCategory = (category: string) => setLocation(category ? `/collections/${category}` : "/shop");
  const submitSearch = (event: FormEvent) => { event.preventDefault(); setSearchTerm(searchDraft.trim()); };
  const clearFilters = () => { setSearchDraft(""); setSearchTerm(""); setMinPrice(""); setMaxPrice(""); setSort("newest"); };

  return <main className="container py-9 sm:py-14">
    <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.12em] text-slate-500"><Link href="/" className="hover:text-cyan-300">Home</Link><ChevronRight className="h-3.5 w-3.5" /><span className="text-slate-300">{slug || "Products"}</span></div>
    <section className="mt-8 rounded-3xl border border-white/8 bg-[radial-gradient(circle_at_75%_15%,rgba(6,182,212,.18),transparent_22%),#101821] px-6 py-10 sm:px-10"><p className="text-xs font-black uppercase tracking-[.17em] text-cyan-300">{page.eyebrow}</p><h1 className="mt-3 max-w-xl text-4xl font-black tracking-[-.05em] text-white sm:text-5xl">{page.title}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400">{page.description}</p><div className="mt-7 flex flex-wrap gap-2">{categories?.map(category => <button key={category.id} onClick={() => goToCategory(category.slug)} className={`rounded-full px-4 py-2 text-xs font-bold transition ${slug === category.slug ? "bg-cyan-400 text-[#061014]" : "border border-white/10 bg-black/15 text-slate-300 hover:border-cyan-300/40"}`}>{category.name}</button>)}{slug && <button onClick={() => goToCategory("")} className="rounded-full border border-white/10 px-4 py-2 text-xs font-bold text-slate-400 hover:text-cyan-300">View all</button>}</div></section>
    <section className="mt-10"><form onSubmit={submitSearch} className="rounded-2xl border border-white/8 bg-[#101821] p-4 sm:p-5"><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_150px_150px_auto] lg:items-end"><label className="block text-xs font-black uppercase tracking-[.12em] text-slate-500 lg:col-span-1">Search products<input value={searchDraft} onChange={event => setSearchDraft(event.target.value)} placeholder="Try Cuban Chain or sling bag" className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-[#0A0A0A] px-3 text-sm font-normal normal-case tracking-normal text-white outline-none placeholder:text-slate-600 focus:border-cyan-300/60" /></label><label className="block text-xs font-black uppercase tracking-[.12em] text-slate-500">Min price<input type="number" min="0" value={minPrice} onChange={event => setMinPrice(event.target.value)} placeholder="Rs. 0" className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-[#0A0A0A] px-3 text-sm font-normal normal-case tracking-normal text-white outline-none placeholder:text-slate-600 focus:border-cyan-300/60" /></label><label className="block text-xs font-black uppercase tracking-[.12em] text-slate-500">Max price<input type="number" min="0" value={maxPrice} onChange={event => setMaxPrice(event.target.value)} placeholder="Rs. 5000" className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-[#0A0A0A] px-3 text-sm font-normal normal-case tracking-normal text-white outline-none placeholder:text-slate-600 focus:border-cyan-300/60" /></label><div className="flex gap-2"><button type="submit" className="inline-flex h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-cyan-400 px-4 text-sm font-black text-[#061014] transition hover:bg-cyan-300 active:scale-95"><Search className="h-4 w-4" />Search</button>{activeFilters && <button type="button" onClick={clearFilters} aria-label="Clear product filters" className="grid h-11 w-11 place-items-center rounded-xl border border-white/10 text-slate-400 transition hover:border-cyan-300/50 hover:text-cyan-300"><X className="h-4 w-4" /></button>}</div></div></form>
      <div className="mt-5 flex flex-col gap-4 border-b border-white/8 pb-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2 text-sm text-slate-400"><SlidersHorizontal className="h-4 w-4 text-cyan-300" /><span>{products?.length ?? 0} items available</span>{activeFilters && <span className="rounded-full bg-cyan-300/10 px-2 py-1 text-[10px] font-black uppercase tracking-[.1em] text-cyan-300">Filtered</span>}</div><div className="flex items-center gap-2"><Filter className="h-4 w-4 text-slate-500" /><select value={sort} onChange={event => setSort(event.target.value as typeof sort)} aria-label="Sort products" className="rounded-xl border border-white/10 bg-[#101821] px-3 py-2.5 text-sm text-slate-300 outline-none focus:border-cyan-300/50"><option value="newest">Newest drops</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></div></div>{isLoading ? <div className="grid min-h-72 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-cyan-300" /></div> : error ? <div className="mt-8 rounded-2xl border border-red-400/25 bg-red-500/5 p-6 text-sm text-red-200">The catalog could not load. Please refresh and try again.</div> : products?.length ? <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{products.map(product => <ProductCard key={product.id} product={product} />)}</div> : <div className="mt-10 rounded-3xl border border-dashed border-white/15 bg-white/[.02] p-12 text-center"><Search className="mx-auto h-8 w-8 text-cyan-300" /><p className="mt-4 font-black text-white">No drops match those filters.</p><button onClick={clearFilters} className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-cyan-300">Reset filters <ArrowRight className="h-4 w-4" /></button></div>}</section>
  </main>;
}
